version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    mysql:

        image: mysql:5.7.27
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./store_files:/store_files_mysql/
            - ./sqlFiles/mysql.cnf:/etc/mysql/mysql.cnf

    webserver:
        #image: puckel/docker-airflow:1.10.4
        image: airflow-custom-ubuntu:latest
        restart: always
        depends_on:
            - postgres
            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local

        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./dataFiles:/usr/local/airflow/store_files_airflow
            - ./sqlFiles:/usr/local/airflow/sql_files
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
# docker-compose -f docker-compose-airflow.yml up -d